JarvusInnovations/emergence-skeleton

php-classes/ActiveRecord.class.php

Added an auto save parameter to the change class functionality.

changeClass autoSave Parameter Update

---

php-classes/Person.class.php

I had to override the whole class to update this error statement, seemed unnecessary.

Make email error a config

---

php-classes/Emergence/Mailer/PostmarkMailer.php

Removed custom logging file in favor of using the Emergence\Logger class.

PostmarkMailer - Updated error logging.

---

php-classes/RecordsRequestHandler.class.php

Splits the search query by spaces and / or word groups surrounded by double quotes.

Added support for quoted search queries

---

php-classes/SearchRequestHandler.class.php

Use generated table alias, instead of static table alias.

Use the correct table alias

---

php-classes/Emergence/Connectors/Exceptions/SyncException.php
php-classes/Emergence/Connectors/IIdentityConsumer.php
php-classes/Emergence/Connectors/IdentityConsumerTrait.php
php-classes/Emergence/Connectors/Job.php
php-classes/Emergence/Connectors/SyncResult.php
php-classes/Emergence/Logger.php

Emergence connectors

---

php-classes/ActiveRecord.class.php

- Allow setting `context-children` type `ActiveRecord` relationships

Set context children relationship value

---

php-classes/ActiveRecord.class.php
php-classes/VersionedRecord.class.php

@themightychris Could you review this please? This resolves an issue caused when saving a record (an exception is thrown).

Abort save if record save is still in progress

---

php-classes/ActiveRecord.class.php

- Store and save context-children relationships
- Optimize relationship saving
- Implement pruning for `context-children` related objects

Set context children relationship

---

php-classes/SQL.class.php

@JarvusInnovations/agu-vps contains override

Create standalone method for getting field definitions

---

html-templates/designs/site.subtemplates.tpl
html-templates/includes/site.css.tpl
html-templates/profile/profileEdit.tpl
html-templates/site-admin/sources/source.tpl
html-templates/subtemplates/icon.tpl

- Add font-awesome
- Fix lingering bootstrap v4 issues in site-admin

Release: emergence-skeleton v1.2.1

---

php-classes/Emergence/Util/Url.php
site-root/css/features/content-editable.css
site-root/js/features/site-search.js
site-root/sass/features/content-editable.scss

- Generalize content-editable color variable names
- Add bootstrap v4 compatibility to site-search
- Accept path array for Url::buildAbsolute()

Release: emergence-skeleton v1.2.3

---

php-classes/ActiveRecord.class.php

- Only store original value once
- Unset original value on reverted fields
- Remove record dirtyness if the only modified field is
reverted back to its original value
- When updating relationships, only set record dirty when
modifying `one-many` & `context-children` relationships.
Other relationship types will modify the record
and internally call `_setFieldValue()` which will
determine whether or not the record is actually dirty

Update ActiveRecord 'dirty' logic

---

php-classes/SpreadsheetWriter.class.php

- Fix autoHeader option when writing to provided fileHandle

Release: emergence-skeleton v1.3.1

---

data-exporters/people.php
html-templates/exports/exports.tpl
php-classes/Emergence/Exports/ExportsRequestHandler.php
php-config/Git.config.d/emergence-skeleton-v1.php
site-root/exports.php

- Add data-exporters infrastructure

Release: emergence-skeleton v1.3.2

---

html-templates/app/EmergenceContentEditor/ext.tpl
html-templates/webapps/sencha.tpl
php-classes/Emergence/WebApps/App.php
php-classes/Emergence/WebApps/IApp.php
php-classes/Emergence/WebApps/SenchaApp.php
sencha-build/EmergenceContentEditor/production/index.html
sencha-workspace/EmergenceContentEditor/index.html
sencha-workspace/packages/emergence-cms/src/view/composer/Markdown.js

- Fix `markdown.js` load paths
- Use absolute paths instead of <base> tag for loading sencha webapps (fixes issues with anchor links)

Release: emergence-skeleton v1.3.3

---

php-classes/ActiveRecord.class.php
sencha-workspace/EmergenceContentEditor/.sencha/app/sencha.cfg

- Only prune many-many values when option explicitly set to delete
- Upgrade sencha-cmd version for EmergenceContentEditor webapp

Release: emergence-skeleton v1.3.5

---

html-templates/webapps/sencha.tpl
php-classes/Emergence/WebApps/SenchaApp.php

- Use new getUrl method in sencha.tpl
- Patch Ext.manifest.resources.path during load
- Move app css loading to <head> to ensure precedence for runtime CSS

Release: emergence-skeleton v1.3.6

---

php-classes/Emergence/DAV/DevelopRequestHandler.php

- Enable /develop login via session token over HTTP auth

Release: emergence-skeleton v1.3.7

---

php-classes/RecordsRequestHandler.class.php

- Enable buildBrowseConditions to export filter object

Release: emergence-skeleton v1.3.8

---

php-classes/Emergence/WebApps/SenchaApp.php

- fix: correct typo in package JS paths

emergence-skeleton v1.3.9

---

php-classes/RecordsRequestHandler.class.php

- feat: handle OutOfBoundsException from buildBrowseConditions

Release: emergence-skeleton v1.3.10

---

php-classes/ActiveRecord.class.php

- feat: add authorizedActions dynamic field and canUser* methods for CRUD

Release: emergence-skeleton v1.3.11

---

php-classes/ActiveRecord.class.php
php-classes/RecordsRequestHandler.class.php

- fix: improve model-based permission handling

Release: emergence-skeleton v1.3.12

---

html-templates/exports/exports.tpl
php-classes/ActiveRecord.class.php
php-classes/Emergence/Exports/ExportsRequestHandler.php

- feat: add support for BETWEEN conditions
- feat: add date types to exporter forms
- fix: print spreadsheet headers for empty results

Release: emergence-skeleton v1.3.14

---

html-templates/exports/exports.tpl
php-classes/Emergence/Exports/ExportsRequestHandler.php

- fix: use ActiveRecord caching during export
- fix: prevent writing second header for 1-row export
- feat: add integer type to exporter forms

Release: emergence-skeleton v1.3.15

---

php-classes/Emergence/Comments/Comment.php
php-classes/Emergence/People/Groups/Group.php

- Repair group and comment validators
- Add applyCommentsData method to Comment model

Release: emergence-skeleton v1.3.16

---

php-classes/Emergence/Git/Source.php

- feat: restore execute mode on already-tracked files

Release: emergence-skeleton v1.3.17

---

php-classes/ActiveRecord.class.php

- feat: add $useTableAliases option to ActiveRecord::mapConditions()

Release: emergence-skeleton v1.3.18

---

php-classes/ActiveRecord.class.php
php-classes/RecordsRequestHandler.class.php

- feat: smarter quoting for number and boolean values
- fix: handle UserUnauthorizedException from buildBrowseConditions
- fix: correct logic when mapConditions operator manually specified

Release: emergence-skeleton v1.3.19

---

php-classes/ActiveRecord.class.php

- fix: handle IN/NOT IN operations against empty arrays correctly

Release: emergence-skeleton v1.3.20

---

php-classes/Emergence/WebApps/SenchaApp.php

- feat: load CSS from sencha app plugins when available

Release: emergence-skeleton v1.3.21

---

php-classes/RequestHandler.class.php
php-classes/SQL.class.php

- feat: use new json column type for json fields
- feat: improve error handling when running wkhtmltopdf

Release: emergence-skeleton v1.3.22

---

php-classes/Media.class.php

- fix: skip advanced cropping on placeholder media

Release: emergence-skeleton v1.3.23

---

.holo/branches/emergence-site/php-classes/Ifsnop/Mysqldump.toml
.holo/sources/mysqldump-php.toml
php-classes/Chaki/Package.php
php-classes/Emergence/SiteAdmin/DatabaseRequestHandler.php
php-classes/Jarvus/Sencha/FrameworkPackage.php
php-classes/Jarvus/Sencha/Package.php
php-classes/Jarvus/Sencha/WorkspacePackage.php
site-root/js/features/content-editable.js
site-root/sencha-cmd/package-build.php
site-root/site-admin/database.php

- feat: add SQL dump endpoint
- feat: add support for building Sencha packages online
- fix: prevent error when markdown value is null

Release: emergence-skeleton v1.4.2

---

.holo/branches/emergence-legacy/_skeleton-v1.toml
.holo/branches/emergence-legacy/dwoo-plugins/builtin.toml
.holo/branches/emergence-legacy/php-classes/Dwoo.toml
.holo/branches/emergence-legacy/php-classes/Gitonomy/Git.toml
.holo/branches/emergence-legacy/php-classes/Ifsnop/Mysqldump.toml
.holo/branches/emergence-legacy/php-classes/Michelf/_markdown.toml
.holo/branches/emergence-legacy/php-classes/Michelf/_smartypants.toml
.holo/branches/emergence-legacy/php-classes/Patchwork.toml
.holo/branches/emergence-legacy/php-classes/Psr/Http/Message.toml
.holo/branches/emergence-legacy/php-classes/Psr/Log.toml
.holo/branches/emergence-legacy/php-classes/ReCaptcha.toml
.holo/branches/emergence-legacy/php-classes/Symfony/Component/Process.toml
.holo/branches/emergence-legacy/php-classes/Symfony/Component/Yaml.toml
.holo/branches/emergence-legacy/php-classes/stojg/crop.toml
php-classes/Emergence/SiteAdmin/DatabaseRequestHandler.php

- chore: add emergence-legacy holobranch
- fix: add support for legacy database config

Release: emergence-skeleton v1.4.3

---

php-classes/SearchRequestHandler.class.php
php-config/SearchRequestHandler.config.php

- feat: order search classes by weight

Release: emergence-skeleton v1.4.5

---

.holo/lenses/sencha-pages.toml

- fix: switch sencha-pages output merge to overlay

Release: emergence-skeleton v1.4.8
